Hardcoded the minimum Forge dependency. This alerts users of the cause of issues such as java.lang.NoSuchMethodError: net.minecraftforge.fluids.Fluid.<init>